[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/.well-known/matrix/*"
  to = "https://matrix.multi.coop/.well-known/matrix/:splat"
  status = 200